name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'       # roda CI só se algo mudar na pasta frontend
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run tests
        run: |
          cd frontend
          npm run test


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # 
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Build and Push to DockerHub
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          push: true # 
          tags: your-dockerhub-username/ci-sum-python:${{ github.sha }} # 
