name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run tests
        run: |
          cd frontend
          npm run test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get next Docker image version
        id: get_version
        run: |
          IMAGE_NAME=leonardo/frontend
          echo "Fetching tags from Docker Hub..."
          TAGS=$(curl -s "https://hub.docker.com/v2/repositories/$IMAGE_NAME/tags?page_size=100" | jq -r '.results[].name' | grep '^v[0-9]\+$' || echo "")
          echo "Current tags: $TAGS"

          if [ -z "$TAGS" ]; then
            NEXT_VERSION=v1
          else
            LAST_VERSION=$(echo "$TAGS" | sed 's/v//' | sort -n | tail -1)
            NEXT_VERSION="v$((LAST_VERSION + 1))"
          fi

          echo "Next version: $NEXT_VERSION"
          echo "version=$NEXT_VERSION" >> $GITHUB_OUTPUT

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: |
            leonardojr96/frontend-dev:${{ steps.get_version.outputs.version }}
            leonardojr96/frontend-dev:latest
